# Generated by Django 2.1.2 on 2018-10-05 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9]+$')])),
                ('email', models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password_hash', models.CharField(max_length=255)),
                ('real_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,}[a-zA-Z ]*$')])),
                ('admin', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('logged_in', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
