# Generated by Django 2.1.2 on 2018-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='real_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
