# Generated by Django 2.1.2 on 2018-10-08 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181005_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9]{1,31}$', 'This field can contain at least 2, at most 32 characters. Only English alphanumeric characters are allowed. First letter must be a letter.')]),
        ),
    ]
