# Generated by Django 2.1.2 on 2018-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
    ]
