# Generated by Django 2.1.2 on 2018-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181018_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, unique=True),
        ),
    ]
