# Generated by Django 2.1.2 on 2018-10-26 18:40

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memorypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to=api.models.upload_memory_media_to)),
                ('memory_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MemoryPost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
