# Generated by Django 2.1.2 on 2018-11-10 14:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181027_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorypost',
            name='tags',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
