# Generated by Django 2.1.2 on 2018-11-13 14:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_memorypost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorypost',
            name='location',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='memorypost',
            name='story',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='memorypost',
            name='tags',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
