# Generated by Django 2.1.2 on 2018-12-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'memory_post')},
        ),
    ]
