# Generated by Django 2.1.2 on 2018-12-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_annotation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('user', 'body', 'target')},
        ),
    ]
