# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
